services:

  mysql:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"

  spring-app:
    build: ./springboot/app
    container_name: spring-boot-app
    ports:
      - "8081:8081"
    depends_on:
      - mysql

  angular-app:
    build: ./angular-app
    container_name: angular-app
    ports:
      - "4200:80"
    depends_on:
      - spring-app
